
name: CBS project continuous intergration pipeline.

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - developer

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

