# testing CI pipeline
name: CBS project continuous intergration pipeline.

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - developer
jobs:
  test:
    name: Running Units Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

