# testing CI pipeline
name: CBS project continuous intergration pipeline.

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - developer

jobs:
  test:
    name: setup env
    runs-on: ubuntu-latest
    
    steps:
      - uses: action/chechout@v1
      - name: use Node.js ${{ matrix.node-version }}
        uses: action/setip-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Instrall
        run: npm install 
    

